# **Fake News Prediction**


# **Objective**

This project is basically based on, to predict fake news. As we all know that in todays world as the social media is spreading all over the world very fast. And as we all know everything has it's own pros and cons. We know that their are many advantage of social media but there are also some disadvantage of it. Not only social media there are many ways of spreading rumors between people. This can be very dangerous to humanity. As we all know there were many cases in past that tell as how rumors was the reason of many deads. So my reason to make this project is to stop all these my of active all over the world. And no more people die due to the rumors.

# **Data Source**

Data source from the github
https://raw.githubusercontent.com/nishitpatel01/Fake_News_Detection/master/train.csv

#**Import Librarys**

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

#**Import Dataset**

In [ ]:
News=pd.read_csv(r'https://raw.githubusercontent.com/nishitpatel01/Fake_News_Detection/master/train.csv')

In [ ]:
News.head()

Statement  Label
0  Says the Annies List political group supports ...  False
1  When did the decline of coal start? It started...   True
2  Hillary Clinton agrees with John McCain "by vo...   True
3  Health care reform legislation is likely to ma...  False
4  The economic turnaround started at the end of ...   True

In [ ]:
News.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10240 entries, 0 to 10239
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Statement  10240 non-null  object
 1   Label      10240 non-null  bool  
dtypes: bool(1), object(1)
memory usage: 90.1+ KB


In [ ]:
News.columns

Index(['Statement', 'Label'], dtype='object')

In [ ]:
News.shape

(10240, 2)

# **Describe Data**

In [ ]:
News.describe

<bound method NDFrame.describe of                                                Statement  Label
0      Says the Annies List political group supports ...  False
1      When did the decline of coal start? It started...   True
2      Hillary Clinton agrees with John McCain "by vo...   True
3      Health care reform legislation is likely to ma...  False
4      The economic turnaround started at the end of ...   True
...                                                  ...    ...
10235  There are a larger number of shark attacks in ...   True
10236  Democrats have now become the party of the [At...   True
10237  Says an alternative to Social Security that op...   True
10238  On lifting the U.S. Cuban embargo and allowing...  False
10239  The Department of Veterans Affairs has a manua...  False

[10240 rows x 2 columns]>

#**Get The Feature**

In [ ]:
x_in=News[['Statement']]
x_in.shape

(10240, 1)

In [ ]:
x_in

Statement
0      Says the Annies List political group supports ...
1      When did the decline of coal start? It started...
2      Hillary Clinton agrees with John McCain "by vo...
3      Health care reform legislation is likely to ma...
4      The economic turnaround started at the end of ...
...                                                  ...
10235  There are a larger number of shark attacks in ...
10236  Democrats have now become the party of the [At...
10237  Says an alternative to Social Security that op...
10238  On lifting the U.S. Cuban embargo and allowing...
10239  The Department of Veterans Affairs has a manua...

[10240 rows x 1 columns]

In [ ]:
x=x_in['Statement']

In [ ]:
x

0        Says the Annies List political group supports ...
1        When did the decline of coal start? It started...
2        Hillary Clinton agrees with John McCain "by vo...
3        Health care reform legislation is likely to ma...
4        The economic turnaround started at the end of ...
                               ...                        
10235    There are a larger number of shark attacks in ...
10236    Democrats have now become the party of the [At...
10237    Says an alternative to Social Security that op...
10238    On lifting the U.S. Cuban embargo and allowing...
10239    The Department of Veterans Affairs has a manua...
Name: Statement, Length: 10240, dtype: object

In [ ]:
x.shape

(10240,)

#**Get The Feature Converted To Tokens**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tfid=TfidfVectorizer()

In [ ]:
x=tfid.fit_transform(x)

In [ ]:
x.shape

(10240, 12196)

In [ ]:
print(x)

  (0, 3278)	0.3399228124530313
  (0, 7728)	0.13423338099593773
  (0, 615)	0.2886717774483849
  (0, 11296)	0.40886628948153914
  (0, 11036)	0.2747906206356454
  (0, 10709)	0.2672566797277703
  (0, 5115)	0.2918323060577216
  (0, 8376)	0.2847775347384892
  (0, 6639)	0.3217759953815641
  (0, 1044)	0.4270131065530063
  (0, 10988)	0.06789988196273675
  (0, 9676)	0.11063502017569249
  (1, 751)	0.18344925558463465
  (1, 1964)	0.2637044974582498
  (1, 4910)	0.20345578434235373
  (1, 8554)	0.13824225599506434
  (1, 5687)	0.06817998938144511
  (1, 1532)	0.2738716739054018
  (1, 11110)	0.07294419071852533
  (1, 10980)	0.10044548692913545
  (1, 7674)	0.19430717148304494
  (1, 11138)	0.184608104001816
  (1, 4860)	0.20468163128243344
  (1, 7418)	0.2540938948798941
  (1, 10426)	0.45919377613538964
  :	:
  (10239, 6853)	0.2728576807709281
  (10239, 10594)	0.2642652775131411
  (10239, 3989)	0.2642652775131411
  (10239, 10918)	0.24004465308468284
  (10239, 8996)	0.20614540733281858
  (10239, 10660)	0.229

#**Get the Predict**

In [ ]:
y=News['Label']
y.shape

(10240,)

In [ ]:
y

0        False
1         True
2         True
3        False
4         True
         ...  
10235     True
10236     True
10237     True
10238    False
10239    False
Name: Label, Length: 10240, dtype: bool

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

#**The Train,Test and Split**

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,train_size=0.8,random_state=252)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((8192, 12196), (2048, 12196), (8192,), (2048,))

In [ ]:
News.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10240 entries, 0 to 10239
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Statement  10240 non-null  object
 1   Label      10240 non-null  bool  
dtypes: bool(1), object(1)
memory usage: 90.1+ KB


#**The Fit Model**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

#**Prediction Model**

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred

array([1, 1, 0, ..., 1, 1, 1])

In [ ]:
y_test

array([0, 1, 0, ..., 0, 1, 1])

#**Accuracy**

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report

In [ ]:
confusion_matrix(y_test,y_pred)

array([[370, 491],
       [283, 904]])

In [ ]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.57      0.43      0.49       861
           1       0.65      0.76      0.70      1187

    accuracy                           0.62      2048
   macro avg       0.61      0.60      0.59      2048
weighted avg       0.61      0.62      0.61      2048

